# Generated by Django 4.2.20 on 2025-04-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_remove_userprofile_name_remove_userprofile_surname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='Cost',
            new_name='cost',
        ),
    ]
