# Generated by Django 5.2 on 2025-04-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Назва виробника')),
                ('year_of_release', models.IntegerField(verbose_name='Рiк випуску')),
                ('model', models.CharField(max_length=15, verbose_name='Модель')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Собівартість')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Потенційна ціна продажу')),
                ('is_sell', models.BooleanField(default=False)),
            ],
        ),
    ]
