# Generated by Django 4.2.20 on 2025-05-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='created_at',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='Дата створення'),
        ),
    ]
