# Generated by Django 4.2.20 on 2025-05-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Назва виробника')),
            ],
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='title',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='auto',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата створення'),
        ),
    ]
