# Generated by Django 4.2.20 on 2025-05-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='title',
            new_name='brand',
        ),
    ]
