# Generated by Django 4.2.20 on 2025-05-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення'),
        ),
    ]
