# Generated by Django 4.2.20 on 2025-05-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_alter_auto_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата створення'),
        ),
    ]
