# Generated by Django 5.1.5 on 2025-02-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Назва виробника')),
                ('year_of_release', models.IntegerField(verbose_name='Рiк випуску')),
                ('model', models.CharField(max_length=15, verbose_name='Модель')),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Собівартість')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Потенційна ціна продажу')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Iмя')),
                ('surname', models.CharField(max_length=15, verbose_name='Прізвище')),
                ('patronymic', models.CharField(max_length=15, verbose_name='По-батькові')),
                ('post', models.CharField(max_length=30, verbose_name='Посада')),
                ('number', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('count_of_sold_cars', models.IntegerField(verbose_name='Продано машин')),
                ('sold_car', models.ManyToManyField(to='worker.auto')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата продажи')),
                ('really_cost', models.IntegerField(verbose_name='Реальная цена продажи')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.auto', verbose_name='Автомобіль')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.user', verbose_name='Співробітник')),
            ],
        ),
    ]
