# Generated by Django 4.2.19 on 2025-02-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
